version: 0.2
phases:
  install:
    commands:
      - echo install NGINX
      - sudo apt-get update
      - sudo apt-get install nginx -y
  build:
    commands:
      - ls
  post_build:
    commands:
      - echo configure NGINX
artifacts:
  files:
    - '**/*'
